name: Unit tests
 
on: # what events trigger this
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: | # for multiple lines
        cd test/unit
        python -m unittest test_utils
